// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiBuddyGames.Infrastructure.Data;

#nullable disable

namespace WebApiBuddyGames.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiBuddyGames.Domain.Entities.Partita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<bool>("Attivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataCancellazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("DataOraDisputa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("partite", (string)null);
                });

            modelBuilder.Entity("WebApiBuddyGames.Domain.Entities.PartitaUtente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<bool>("Attivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataCancellazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PartitaId")
                        .HasColumnType("integer");

                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.HasIndex("PartitaId", "UtenteId")
                        .IsUnique();

                    b.ToTable("partite_utenti", (string)null);
                });

            modelBuilder.Entity("WebApiBuddyGames.Domain.Entities.Risultato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<bool>("Attivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataCancellazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PartitaId")
                        .HasColumnType("integer");

                    b.Property<int>("PuntiPrimaSquadra")
                        .HasColumnType("integer");

                    b.Property<int>("PuntiSecondaSquadra")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartitaId")
                        .IsUnique();

                    b.ToTable("risultati", (string)null);
                });

            modelBuilder.Entity("WebApiBuddyGames.Domain.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<bool>("Attivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataCancellazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("utenti", (string)null);
                });

            modelBuilder.Entity("WebApiBuddyGames.Domain.Entities.PartitaUtente", b =>
                {
                    b.HasOne("WebApiBuddyGames.Domain.Entities.Partita", "Partita")
                        .WithMany("PartiteUtenti")
                        .HasForeignKey("PartitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiBuddyGames.Domain.Entities.Utente", "Utente")
                        .WithMany("PartiteUtenti")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partita");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("WebApiBuddyGames.Domain.Entities.Risultato", b =>
                {
                    b.HasOne("WebApiBuddyGames.Domain.Entities.Partita", "Partita")
                        .WithOne("Risultato")
                        .HasForeignKey("WebApiBuddyGames.Domain.Entities.Risultato", "PartitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partita");
                });

            modelBuilder.Entity("WebApiBuddyGames.Domain.Entities.Partita", b =>
                {
                    b.Navigation("PartiteUtenti");

                    b.Navigation("Risultato");
                });

            modelBuilder.Entity("WebApiBuddyGames.Domain.Entities.Utente", b =>
                {
                    b.Navigation("PartiteUtenti");
                });
#pragma warning restore 612, 618
        }
    }
}
